services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=elvia-unspecific-arlo.ngrok-free.dev
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://elvia-unspecific-arlo.ngrok-free.dev/
      - WEBHOOK_TUNNEL_URL=https://elvia-unspecific-arlo.ngrok-free.dev/
      - N8N_EDITOR_BASE_URL=https://elvia-unspecific-arlo.ngrok-free.dev/
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_LICENSE_ACTIVATION_KEY=0bcb1d90-ef0e-4502-8449-5b1786e65c31
    restart: unless-stopped
